# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'desafioIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafioIOS
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.0'
    pod 'ObjectMapper', '~> 2.2'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'Kingfisher', '~> 3.0'

end
